development:
  adapter: postgresql
  encoding: unicode
  database: uctads_development
  host: localhost
  pool: 5
  timeout: 5000
  username: postgres
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: uctads_test
  host: localhost
  pool: 5
  timeout: 5000
  username: postgres
  password: password