# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

cat_1 = Category.create(name: "Automotive", fields: {}, parent: nil)
cat_2 = Category.create(name: "Cars", fields: {"Make"=>{"optional"=>false}, "Model"=>{"optional"=>false}, "Year"=>{"optional"=>true}, "Gearbox"=>{"optional"=>true, "select"=>["Manual", "Automatic", "Tiptronic"]}}, parent: cat_1)
cat_3 = Category.create(name: "Motorcycles & Scooters", fields: {"Make"=>{"optional"=>false}, "Model"=>{"optional"=>false}, "Year"=>{"optional"=>false}, "Engine Capacity"=>{"optional"=>true}}, parent: cat_1)
cat_4 = Category.create(name: "Parts & Accessories", fields: {}, parent: cat_1)
cat_5 = Category.create(name: "Electronics", fields: {}, parent: nil)
cat_6 = Category.create(name: "Cellphones", fields: {}, parent: cat_5)
cat_7 = Category.create(name: "Computers", fields: {}, parent: cat_5)
cat_8 = Category.create(name: "Laptops", fields: {}, parent: cat_7)
cat_9 = Category.create(name: "PCs", fields: {}, parent: cat_7)
cat_10 = Category.create(name: "Components", fields: {}, parent: cat_7)
cat_11 = Category.create(name: "Accessories", fields: {}, parent: cat_7)
cat_12 = Category.create(name: "Game Consoles", fields: {}, parent: cat_5)
cat_13 = Category.create(name: "Audio Equipment", fields: {}, parent: cat_5)
cat_14 = Category.create(name: "Cameras", fields: {}, parent: cat_5)
cat_15 = Category.create(name: "Fashion", fields: {}, parent: nil)
cat_16 = Category.create(name: "Clothing", fields: {}, parent: cat_15)
cat_17 = Category.create(name: "Shoes", fields: {}, parent: cat_15)
cat_18 = Category.create(name: "Accessories", fields: {}, parent: cat_15)
cat_19 = Category.create(name: "Books", fields: {"Title"=>{"optional"=>false}, "Author"=>{"optional"=>false}, "Publisher"=>{"optional"=>true}, "ISBN Number"=>{"optional"=>true}}, parent: nil)