source 'https://rubygems.org'

gem 'rails', '4.1.0'

gem 'sqlite3'

gem 'haml-rails'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'bootstrap-sass'
gem 'font-awesome-sass-rails'
gem 'turbolinks'

gem 'jbuilder', '~> 1.2'

gem 'closure_tree'

gem 'paperclip', '~> 4.1'
gem 'aws-sdk'

group :doc do
  gem 'sdoc', require: false
end

group :development, :test do
    gem 'faker'
    gem 'rspec-rails', '~> 3.0.0.beta'
    gem 'cucumber-rails', :require => false
    gem 'database_cleaner'
    gem 'factory_girl_rails', '~> 4.0'
end
